export const GET_ITEMS = 'GET_ITEMS';
export const ITEMS_LOADING = 'ITEMS_LOADING';

export const GET_ONE_ITEM = "GET_ONE_ITEM";

export const BAG_LOADING = 'BAG_LOADING';
export const GET_BAG = 'GET_BAG';
export const ADD_TO_BAG = 'ADD_TO_BAG';
export const DELETE_FROM_BAG = 'DELETE_FROM_BAG';

export const REQUEST_LOADING = 'REQUEST_LOADING';
export const GET_REQUEST = 'GET_REQUEST';
export const REQUEST = 'REQUEST';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const STOP_LOADING = 'STOP_LOADING';

export const RESERVATION_LIST_REQUEST = 'RESERVATION_LIST_REQUEST';
export const RESERVATION_LIST_SUCCESS = 'RESERVATION_LIST_SUCCESS';
export const RESERVATION_LIST_FAIL = 'RESERVATION_LIST_FAIL';


export const RESERVATION_DELETE_REQUEST = 'RESERVATION_DELETE_REQUEST';
export const RESERVATION_DELETE_SUCCESS = 'RESERVATION_DELETE_SUCCESS';
export const RESERVATION_DELETE_FAIL = 'RESERVATION_DELETE_FAIL';